export const SWITCH_WIDTH = 40;
export const SWITCH_HEIGHT = 24;
export const SWITCH_PADDING = 3;
export const SWITCH_CIRCLE_SIZE = SWITCH_HEIGHT - SWITCH_PADDING * 2;
export const SWITCH_CIRCLE_OFFSET =
  SWITCH_WIDTH - SWITCH_PADDING * 2 - SWITCH_CIRCLE_SIZE;
export const SWITCH_BORDER_RADIUS = SWITCH_CIRCLE_SIZE + SWITCH_PADDING * 2;
export const SWITCH_ACTIVE_CIRCLE_WIDTH = SWITCH_CIRCLE_SIZE * 1.3;
export const SWITCH_CIRCLE_WIDTH_DIFF = SWITCH_ACTIVE_CIRCLE_WIDTH - SWITCH_CIRCLE_SIZE;
export const SWITCH_ANIMATION_DURATION = 250;
