export enum AuthScreensNames {
  Start = 'Start',
  AuthStack = 'AuthStack',
  SignUpOrResetPassword = 'SignUpOrResetPassword',
  SignIn = 'SignIn',
}

export enum MainScreensNames {
  MainNavigator = 'MainNavigator',
  SwapNavigator = 'SwapNavigator',
  Main = 'Main',
  Wallets = 'Wallets',
  WalletsNavigator = 'WalletsNavigator',
  Swap = 'Swap',
  SwapRate = 'SwapRate',
  SwapInsufficientFunds = 'SwapInsufficientFunds',
  SwapSuccess = 'SwapSuccess',
  Exchange = 'Exchange',
  UIKit = 'UIKit',
  Notifications = 'Notifications',
  Wallet = 'Wallet',
  HistoryItem = 'HistoryItem',
  CurrencySend = 'CurrencySend',
  CurrencySendSuccess = 'CurrencySendSuccess',
  CurrencyReceive = 'CurrencyReceive',
  FiatRefill = 'FiatRefill',
  FiatWithdrawal = 'FiatWithdrawal',
  BankNavigator = 'BankNavigator',
  BankList = 'BankList',
  BankMethodList = 'BankMethodList',
  BankMethod = 'BankMethod',
  FiatWithdrawRecipient = 'FiatWithdrawRecipient',
  FiatWithdrawConfirm = 'FiatWithdrawConfirm',
  Settings = 'Settings',
  Language = 'Language',
  Appearance = 'Appearance',
  Personal = 'Personal',
  BiometricsPincodeSettings = 'BiometricsPincodeSettings',
  SetPincode = 'SetPincode',
  SecureGateNavigator = 'SecureGateNavigator',
  SecureGate = 'SecureGate',
  PincodeValidate = 'PincodeValidate',
  BiometricsValidate = 'BiometricsValidate',
  PersonalLogin = 'PersonalLogin',
  PersonalEmail = 'PersonalEmail',
}
